### PR TITLE
Fix ValueError thrown on specific byte sequence

### PR DESCRIPTION
**Pull request by adamsqi**
There is this issue that appears in the recent version of the package:
```
ValueError: b'\r\n' is not in list
```

The bug has been fixed in the recent version of https://github.com/delimitry/aztec_code_generator
More about the issue and the fix: https://github.com/delimitry/aztec_code_generator/issues/7

### CODE REVIEW

**Comment by dlenski** [comment]
This PR doesn't apply to the `master` branch of this repository _at all_. Did you try it?

**Comment by adamsqi** [comment]
Yes it looks like this is the significant part except of formatting.

**Comment by dlenski** [comment]
I'm not convinced that the solution from https://github.com/dlenski/aztec_code_generator/pull/4 is a very clarifying or complete one. For now, I've just added a (failing) test to demonstrate the problem in 41dce81.

**Comment by adamsqi** [comment]
@dlenski 
I think this PR can be closed, since the fix needs to be added in a new PR.

**Pull request closed without merging**
